### ISSUE TITLE
Enclose GH action secrets within proper quoting rules

### ISSUE THREAD

**Issue by hanefi** [citusdata/packaging#740]
Github recommends that we enclose all our secrets that are passed within a commend line.

Here is the excerpt from [GH docs](https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow):

-----------------------------------

If you must pass secrets within a command line, then enclose them within the proper quoting rules. Secrets often contain special characters that may unintentionally affect your shell. To escape these special characters, use quoting with your environment variables. For example:

Example using Bash
```yml
steps:
  - shell: bash
    env:
      SUPER_SECRET: ${{ secrets.SuperSecret }}
    run: |
      example-command "$SUPER_SECRET"
```
