### ISSUE TITLE
Add os release exclusion mechanism into postgres-matrix.yml

### ISSUE THREAD

**Issue by gurkanindibay** [citusdata/packaging#958]
Currently, we manage os/release-postgres match exclusion in pg_exclude.yml. We can merge this into postgres-matrix file as below

```yml
name: Postgres Version Matrix
project_name: citus

version_matrix:
  - 8.0:
      postgres_versions: [ 10, 11 ]
  - 9.0:
      postgres_versions: [ 11, 12 ]
  - 9.5:
      postgres_versions: [ 11, 12, 13 ]
  - 10.1:
      postgres_versions: [ 12, 13 ]
  - 10.2:
      postgres_versions: [ 12, 13, 14 ]
  - 11.0:
      postgres_versions: [ 13, 14 ]
  - 11.1:
      postgres_versions: [ 13, 14, 15 ]

exclude:
  nightly:
    ol/7: [ 15 ]
  release:
    all: [ 15 ]
```
